/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const FETCH_BLOCKS_START = 'FETCH_BLOCKS_START';
export const FETCH_BLOCKS_ERROR = 'FETCH_BLOCKS_ERROR';
export const RECEIVE_BLOCKS = 'RECEIVE_BLOCKS';

export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';

export const FETCH_PICTURES_START = 'FETCH_PICTURES_START';
export const RECEIVE_PICTURES = 'RECEIVE_PICTURES';
export const FETCH_PICTURES_ERROR = 'FETCH_PICTURES_ERROR';

export const FETCH_ACCOUNTS_START = 'FETCH_ACCOUNTS_START';
export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const FETCH_ACCOUNTS_ERROR = 'FETCH_ACCOUNTS_ERROR';

export const SET_SELECTED_ACCOUNT_START = 'SET_SELECTED_ACCOUNT_START';
export const SET_SELECTED_ACCOUNT_ERROR = 'SET_SELECTED_ACCOUNT_ERROR';
export const SET_SELECTED_ACCOUNT_COMPLETE = 'SET_SELECTED_ACCOUNT_COMPLETE';
